language: go
go:
  - 1.11.x

# branches:
#   only:
#   - master
#   - /[\d+.?]+/

addons:
  apt:
    packages:
    - docker-ce

sudo: required

services:
- docker

env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: zXF8+zTvDC0qM0F6MOk9cDLpN49oeuLrBTnpzGP88Isd7wct51epj5Zf58v53KN1qZCz62+o+vgI2EJQwtgSBCIhfXZTblUrBPJSyKyxBpz7EnajQsUQWsNZnL5/Lh8B+pY4C7YgU2tSucxIJnXrtPv4PyM/S9JdXOw3dmaUfvgHRxuxvzUAJKlRKomEBF6XYPpPLABNNI23qhhMbRbnud01Pme5XUyyYGpj5fcB9L6b0MwvhDJRfnuE+Q4ytVZBCfgbbT1yXkfKLVMitzJmsbEFCRPMUSRKrkqeLvUNpgXLZbgZcFdCHuGaGvTbeI0fOxm9J1cwrYI6Yptt4/+ww4j8dKtj9lMSmqonuD7ngL5WgLgowzKxC+9bg2CDNQJTPp9tIE1iUtEqM3AkHEqP6Y0QnI0xDjnXM2MLUAiz/h8wZXCERgXeyKojoShA9pDqM+jAhY4z3lGDuU6Ewe1+wlS8ovh1QjGaTQbHfEQ1XcDyOf5YkAahb7oVJ19/2sM58L5Mu24AoNi/FuZBHBS3wfJN8IBPxX5Rkhcl34ShJ1clqtQmNVs1JML6g1WP5GNaOPdQxvbNlqmIAGH6duVxe8VTKMl0ir3+tCQcrvxYvi/f6TKLkFu3b/jCs4DwWhax5EgLs36R7OPLYmInGmuHYMFooe1l9l5iF/57ZE/v/Io=
    - GO111MODULE=on

jobs:
  include:
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make test
  # --------------------------------------------
  - stage: build+push:latest
    if:
      tag IS NOT present
    before_deploy:
      - make build TAG=latest
      - make run TAG=latest CMD=version
    deploy:
      provider: script
      script: make push TAG=latest
    on:
      branch: master
  # --------------------------------------------
  - stage: build+push:tag
    if:
      tag IS present
    before_deploy:
      - make build TAG=$TRAVIS_TAG
      - make run TAG=$TRAVIS_TAG CMD=version
    deploy:
      provider: script
      script: make push TAG=$TRAVIS_TAG
    on:
      tags: true
      all_branches: true
  # --------------------------------------------
