language: go
go:
  - 1.11.x

branches:
  only:
  - master
  - /^[0-9.]+$/

addons:
  apt:
    packages:
    - docker-ce

sudo: required

services:
- docker

env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: fB9Tcxsget5LYxpZAJek4qFe+U0VyDcE7kSGAfc79wikcqbUpAy26fW6NkA522Jo95JPwt1Z0IKdDs5aPrLVnM1LSEWd3tAMpsfUUZZBnWCW5uxO8U5FxkaT6Sk6ymFAy8MpjvbUJUEZk850tjvsO0fGUnt3g98uIqB253nLNTmkrVvepnk5pdi3rxodNIzP02DizhQVCVTYlCei+rzHXIzpKbyuEpAlCc1fs4MnmshcxzndM9n+ZGeAHpX9RJU7qyhLaEdgpTkN3Ig+x9bSK9TbvkK+Iq/vPB+J3loNb/U0xr+W62YMaX48hfQbc9yvBLr76ktjvI4LPuocil2FFhdtHQFLwoeSRjeel9TtjV3Oy2fIRktrIlZmgfwGmc9vVZKPA9vD+YZKj2mklYjCIjwmcOXnj1zehuaYPaff3LP/lNOL3J5aszPRpRswfYJ8QCixEZ4hrh4h+fQO/Umue9pfDy4SecgifhFF6mwtwFSdbpFco9iWu2Jvrb4rtfzRfhwie9AFY/iTXgiN0s4E8CVbsDoxQeKR7vGSWeEq/kcoyxLAzTy6rIjQ/VVuNAkvY5Ojw5vhiF3XFQ5+fpuDu/jxhy/oROks+F/D+Mk1112sy3oEU557RqcYNTLqjNwF20gz0YSx2FKwQ49uAAoaRNKj495RvNw9IpjxE1EH/cs=
    - GO111MODULE=on

jobs:
  include:
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make test
  # --------------------------------------------
  - stage: build
    skip_cleanup: true
    script:
      - make build
      - make run CMD=version
  # --------------------------------------------
  - stage: push:latest
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=latest
      on:
        branch: master
  # --------------------------------------------
  - stage: push:tag
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=$TRAVIS_TAG
      on:
        tags: true
  # --------------------------------------------
