language: go
go:
  - 1.11.x

branches:
  only:
  - master
  - /^[0-9.]+$/

addons:
  apt:
    packages:
    - docker-ce

sudo: required

services:
- docker

env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: o26Y9C73hmyz1Otqokc9cXTyfFiNgvq0TQJKMHVXqTwwjN4ZS24uWGzuz0uVT0tb99dDaMj8OZYCuE0EQv/8tgDSfyyXkVT3jxRN8IYlQTYmH1EJ9IUNy3+Bna6WILBDdIb7cq0VKe6aCnXwLYu6aekFRyp+aXOWLPI5XHp6g94UdXn0ydd5P6ccxCkZbZpsO061oReyWulTMBgl79k8VwsIVQZOJoU3NxObsgNYlnAJRGpKr/5q18wmYNqsCvbxrOoeaWkMXZzo5cfN4UjbLHp1ppG1j5DCxsKIugpV8fLMx/gm5c3pnTTwzpSWyDEPGD7CSPRkSSIKrMZF28YS2jcDIhLe+BVCv6Cx1I4IOfT394rlBarIgB+zCpLU/g2HRHzxXuHqdgUvSr0MGFSgALXMpKL8geKZBL7cTti71RnXpzrkX0vZdaDKolZI59o59SIcFqcuj6rIG93P9KCBmKSvJ6vyS+BMYbQzM1YJE6HxZLQWht+VfKR3NZLfFEQAHNa8QWq0I54XaCo4PZ/WHAvDqQyBRcKo0vi5ZbHcvAjwZmdGeRD7CJ0B+JExmlwySRdkPxkZvi/ykD+YaE9vpFLZNwfR3ku9VeRceJuo99xcE7PUzv+Ym4zUl3X34+xmxav/88wefHVnWmrStqVpZ63SlQXJgsDRM7VSclc44Z8=
    - GO111MODULE=on

jobs:
  include:
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make test
  # --------------------------------------------
  - stage: build
    skip_cleanup: true
    script:
      - make build
      - make run CMD=version
  # --------------------------------------------
  - stage: push:latest
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=latest
      on:
        branch: master
  # --------------------------------------------
  - stage: push:tag
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=$TRAVIS_TAG
      on:
        tags: true
  # --------------------------------------------
