language: go
go:
  - 1.11.x

branches:
  only:
  - master
  - /^[0-9.]+$/

addons:
  apt:
    packages:
    - docker-ce

sudo: required

services:
- docker

env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: QiqhPo+gbWiUqAAQq3tjRqjM8mN1i1oEVYVDwen1wFH+ts/1fuQN1KuWeXyZ8Xf/+CvrhXSXH31p4xl4cVuBBM+6zAa5xH1vAv3p3EEDnpOYzzmTsDi5SIWN1HYBytjHE0PnRMNgxj5mj+5wNMoVyRGSzFtwZMPZ7pCe4hxzwuYvJ05i/fkQyT9CDE1mL6B3UuwTfg2urBTf86FtXUnRxitDNjQaRCpGTAVex/SClUmBGAdEzDfCuP4tkooMtvAcVXiWjOXpYvYQOKIocGwHgd6dBuZBnNVKnDzaC2i3jYLJze/GKKocMnPCQYWG3ZnRUwFQhFGf3wKbBBassVEQDjsN7VobNoC2asXc3Bz2sqdCPRfcF0WOvI6tdpDzgcyPcNgn7BdMrQPLJdWr4Sn9a/acPAhTspjYUkDS5dadaWbVRIaJpLmzIqoE8z+qZVTBHisje3AWoU9wG9czLs2bxONBgJJigcpSlAXrAn0QOWNOnurKbrDHXxSOvvATI2mgj9DQ99P4fEHyq1YmfcikBnGCeZP++pblKtyM/0cdWzvhKR9xHInGVZUgMkhmbZM9AwOSNymKONKt2BMAXsK0/sjY8nPpwfiEQtGcXe4SwIEGnaXSn1rlawWxnteerYOo86Wm8QZjd7wocU0IhKcCLZOOvwLzczvT8PcsEOZBL5A=
    - GO111MODULE=on

jobs:
  include:
  # --------------------------------------------
  - stage: login
    skip_cleanup: true
    script: 
      - make login
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make test
  # --------------------------------------------
  - stage: build
    skip_cleanup: true
    script:
      - make build
      - make run CMD=version
  # --------------------------------------------
  - stage: push:latest
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=latest
      on:
        branch: master
  # --------------------------------------------
  - stage: push:tag
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=$TRAVIS_TAG
      on:
        tags: true
  # --------------------------------------------
