language: go
go:
  - 1.11.x

branches:
  only:
  - master
  - /^[0-9.]+$/

addons:
  apt:
    packages:
    - docker-ce

sudo: required

services:
- docker

env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: h9Yq4iWSM9WlMc5iIZs5/PbaGKjVnji4M4TpQHhzIRKF6/cnBSWBGHpG5DOrlS8fi1XOoX11RYbxHjg+pD71r3YdAndtZXnvWMm2CHaakhteGy+1Q1nzpQZZeiQKSlFAt2LEAf5FKqObU4jZt1XxFmdGwb1B/XhzZZ3SAFL5vDu9I0DxWdULB9eekdzR9AMvvKYgLKLPPFFxVO8a/3xZ9FE0YyaV9lUzOELjM6xGD5ieCgMBN0kP8jKL0uCuVf1S69+/GLqCjexkuKzbVNvdYTsvddpPXEP31Au3+bsfO1RCSQKt+RvDnoOlCpHHYTHKwUUC+PzhqtGRVCLWDISfEFmOrCW3Bi7a8hCChs+vwtKioexpeCNMDPdn1GaYkSDpaolfPOnX/Sdub3RphLNhev6wtHOIFKYXl8C7sdJ2pK7ioJZGQXI1UMOIZalFnqvzL8lt9Yxf6V8pCeGpZiUxHvehMI+TozWsBSapeBMp2nj/thD724Qs7KLwJTQuIguPUwNZSR70QZnNFbLxPny2v/7APNq+rEvVkXphD3eLXmnFOJV+TC8cNCsOXoOMgFl6D4758eZIsPOQiBlt6UTbEJXr6ETDD3q8RI3AVQC05XtRc0RO/NwrIPuWpB4/CutZ9tdqf7cc4V4KsPgkY9Qp+XOcEwjg/dl0sLU3SAObOuw=
    - GO111MODULE=on

jobs:
  include:
  # --------------------------------------------
  - stage: login
    skip_cleanup: true
    script: 
      - make login
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make test
  # --------------------------------------------
  - stage: build
    skip_cleanup: true
    script:
      - make build
      - make run CMD=version
  # --------------------------------------------
  - stage: push:latest
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=latest
      on:
        branch: master
  # --------------------------------------------
  - stage: push:tag
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=$TRAVIS_TAG
      on:
        tags: true
  # --------------------------------------------
