language: go
go:
  - 1.11.x

branches:
  only:
  - master
  - /^[0-9.]+$/

addons:
  apt:
    packages:
    - docker-ce

sudo: required

services:
- docker

pre_install:
- go test -v ./...

env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: QS0nBje5L3zAMBIUIcnZxQ/YZt93PLxoGiFhZyXOYuqyBsFRL55M2M3ErOOMz5/IS371zXN7OJIlvUjUj1k/XGJAYt/euivRLAn5BJND7RE1SiCOXpaDxCNjE6vr9pP3hG4T1qpadiiwiR+7D/EqKX1A6NO1znVVD8j+IpeEbVk90i5bhv85aermgR193JO4P7Q89NXmAKPgPji1ZhdqEkaGSuYd3tG8DPIvHetVoIvB620D3LA1xVYlkkDRHd/u9oT5JzKCmkUDiGwJeWoYFYdcXhf92hSxyihlUItWXd1kmEuaiBIe7u6f6UkFIDSadMBsM34eZ9ZSeclS5rNXC5Zup6P7qbzjZpoXQIwShQhuUh/3NN/5cXVMGPJ4E24qaXyxb1aqd2C8LBy/VoGyZe+wqoR9EvvEILtdsV/idHa0Aw9YrR+kiowmpUTFINrRG4M1mrYB7ZH67i+kX51LEyOGe9s9pQN4NWEoAyspZCJ7V2zZ5UyhEN6T4+1imdj4h0Rq1LJ62T0pudP7nwiaiKP3AV4/CQnfMjr4sHu0CcE2UndzbARRFk7U6OHhmsMm1zZ+aaS7ZGQLt5hHVpDpoQiZAo6yxLPfq6izBG3Tzf61fl9JB6lKYUHgeppSWkLrIsSG0agYXU7xPV6KtLqWd37UO+329hAXKk36J1nci7I=

jobs:
  include:
  # --------------------------------------------
  - stage: docker build
    script:
    - make build
    - make run CMD=version
  # --------------------------------------------
  - stage: docker push
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=latest
      on:
        branch: master
  # --------------------------------------------
  - stage: docker push
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=$TRAVIS_TAG
      on:
        tags: true
  # --------------------------------------------
