language: go
go:
- 1.11.x
branches:
  only:
  - master
  - /^[0-9.]+$/
addons:
  apt:
    packages:
    - docker-ce
sudo: required
services:
- docker
pre_install:
- go test -v ./...
env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: V+j0OVsL2Vvgmg1rr2hBffR2eK0bvq9smjaWXpYDbuIFQr0HEd01ODiZGohY6QiZNmwuCJzhn++pQHBcNBAwl5s0knsqSUAnNmB2ipFwg1WCBFoZLyQqhvZMmrwK9OWbwjtSldB9off/oo12rgAW8ZAVpsAt7CN5Vt/8EbgDZsISxSwmSfy46SpIaEf8+ZpvtsJYJJsU4akoY+DPhA5DIv2Z6KYSCSvNey9NDpEeYhan94pvvDzaUosxmdiiaUoKY/Re8NkoLdcVHXjp65TcCJfMTuNAuTYAgB5GKlfkkiQT5CQgZ/YhOb7jyyvDJr050uIr9na/q6HKuS7yS06X2OrtQd96xvRj24CdROmUi0rUZZ/WtTHENrxNmWn48iPXebzrFM+dmYHB9DadPxYO6YrATgVprLbhSv8Z1I55Dl/blI4jgB1zAbYPGAfMK1OScUjbRF4wRmQJkz88MEE6Dv7ybZAl66HkHvK+LFcMDpYqlphpkGGAsgrOCw0QIMe8A3RA4xJ+/hE+RCI/xm2x2eAVFDL62S026sAzzBLgBexye/d0F0OiXR1/iEM1iFLLTRuFoDbYn35CLgMeKrUezKhUzPX/HWBIi8MnYhMHV8Liu4v/DvXHKCuX1DqHgpbMu3UpFP7kBypIAQaXDizt4r7R06RfF6ptRF3VEQ/DMpc= # pass

script:
- env
- docker build -t alexleonhardt/gocd-seeder .
- docker run --rm alexleonhardt/gocd-seeder version
