language: go
go:
  - 1.11.x

branches:
  only:
  - master
  - /^[0-9.]+$/

addons:
  apt:
    packages:
    - docker-ce

sudo: required

services:
- docker

env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: pXlm98GNQ6y+mMM6+Wzvz6Plv0qedwWeqLhrcSLsjp9toX15JR2pxQfpzWiyvSsQFe/fYuE9pCZ7Aquur0nTEQvC/BbODIkM6WPyKB1pHl10paY+QHOHP5slws/31n12cgGPY9jP5BvTBnV4M6in8obNElQfwz5EnFQThFW2OvlmFUmBAFNroFjhR/aTxBw5k31e13KGrcynHX6VAKWG+tYXo21tqyfs+zPFqVnhJ1AGtCL11vdk6o4RAkCRtl9EdTVTXM/0CPQCQv63CnHP+A769DpxmozlrpAPBXvt0SbAQ6g0t+Lur2Bk+AAkD8HdS2DpXH5IxMkdzHNPCbvZsGauF/UF6H3Ad+OGLsWgeZN2QnDsFxuDf/dQR2psS5oRU5Ueo6cnIPbUAPjWdlIkfqgbOeiG4mhF2B+DISHyGY51s9EKxP1tlDAiMVY8oPjJGod9t/ot/HcnojOvKTR8nRsQFYq9JfT8kFQfavGLJENzDTQjcWYOT+MFH3vKq+jlzcJeUwcbiWgUuC4xLAzQI+/HOQVVQcEUYRUmU2L278NRoHzFStkvSJYkEeWw3C7XLytAYhL3DL3iwP2nca3/R+EBK2dIWTqUek+htcfJuZiacha3B7ogCkAGjnJ5zZ8j2fQ5e65a26yJ28wNRam3w0qERDJvoQecGMxoMRHd+Co=
    - GO111MODULE=on

jobs:
  include:
  # --------------------------------------------
  - stage: login
    skip_cleanup: true
    script: 
      - make login
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make test
  # --------------------------------------------
  - stage: build
    skip_cleanup: true
    script:
      - make build
      - make run CMD=version
  # --------------------------------------------
  - stage: push:latest
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=latest
      on:
        branch: master
  # --------------------------------------------
  - stage: push:tag
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=$TRAVIS_TAG
      on:
        tags: true
  # --------------------------------------------
