language: go
go:
- 1.11.x
branches:
  only:
  - master
addons:
  apt:
    packages:
    - docker-ce
sudo: required
services:
- docker
pre_install:
- go test -v ./...
env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo=
    - secure: mKXuX8sOxOAHWms6lfZDylkH/FDeOto2AZ+GXRfssSvm7Fr8MoFW0qtyGr8l6++E63078zeBOfD2YOK/lqeLlJXHd47Y5RMIVreKSGfU7CVi9uBY1uRsaCg2dtG/4wSAUVyfgGOXgY9gRYE0fZy7rGl9Rar10QB4wQuXcTpr4nbDLUvXFEqaApa/+eZtf2DWLw8moeg6dw2QAmOIUTWv10ka1ULl/ihoF+9i7vwDlIxTOql5GeI54iBf6Q6QO+MAi+UEe9CM2aj9KOMuzcF1PCHHpuiEhdde4+kUyHBBviff1rBALwfuvGzW/7Tdg2UL97AlS0BoaOpUGqb3WbOeqhzy7fVwQH/DIvf9npYdUGk3GrUg0+Xaf7UmnA4BVZnn9IlepP0YRLviLy2zGfjlMoQcKWKME3x7XdVj9YtjS1TYo1KxrNFMAr8cZ4YisrPznm1hLM3o9S9ME27lfsIvk1SaEjGpl8Ldn8qoHf/6ZFml0A+oZZx6TPfaMVcABI3gERpm2lrO4DbaUMq24Baw9cbx6QKHlZe3qTs8XOIFw9+Af+dUFw5HDQlWz6aP4RCdEUil7yM8q8Qz4yuU6/2JlBvPKR3d/lVj/1i8ePvJF2oCafvO/wXqiPjHOsNxrvuOWufgOVepzzIIauYeWOdtn+boGXC144nYMVJ2DkiKlqM=

script:
- env
- docker build -t alexleonhardt/gocd-seeder .
- docker run --rm alexleonhardt/gocd-seeder version
