language: go
go:
  - 1.11.x

branches:
  only:
  - master
  - /^[0-9.]+$/

addons:
  apt:
    packages:
    - docker-ce

sudo: required

services:
- docker

env:
  global:
    - secure: Ck354xSy5HCOwumR0YeqyT2y/w2ID8I/P54SO2YstuAkrKh3b487cXiqqzfmL9VuMvFlRosxv99cCGj7pG+0pjBm1dLiYSryq5/DabqBpdIgbq4QRn/gScy9od98cJ6qeTVjctWFe5MK7xlWxKSsVuh1Y/HVdXmYjZa/RFXrJ7pgIBpgzF+IXL2VwPhamA3XOAxXNdel/XKPqnkY1PMsIrbmwqL7Zd+7mzrkar5+vap2BgVhnuwyvORh7z9iwUTYL4FPsXZ/FfLEH4vFZxThPZJBLZ12R9KJtrdpXCKVGGxbXuFDEYi0sSwbGoPF7ezjjyhKwdGwM2B15IzesiVy8Sy10VWyVY47mrTiylr7r5cBhEpFAM0o6mW/klAwK4Mg9oEJ3bIUUV5DUkKPOBxe6xSKJhSwpcitbfGQVGVF3HN6SNNFbkigpnw0Xm0RDHeTqLaXcIXvCPBOoioi0rcGM7Lkx1df8ptdX5QQtbt2dPLoc8Ji0zBtKYwIPMqCwDAnMPGScYbAl1mJVBEAMMRAlNEQJjDWA2HpDlEQurGJC7s3POngLBKDDOq87liDEZ+z6+FeDvezDtpbugt5w7BwEHBRYCtwNrVNZpe8fTc9ffPkJYnj/A1uiOPSEShG6bynana3LgcViXJCuOpljAuTHCcHWwiGmk8aXGbGXdlKJgo= # user
    - secure: ofe1b+kNlYCQVCIPIMIOydPLpeKADki4QOUbTcYBNpRfOwI4oBFNPgaheiqHjA//D0s9wTDpRmph/P3fVj8b9S0/eIw2YAzoJaXPjLifYAEZMpLzAnrIpHnvem7Gq1rjvGdlzPO0m3fyUogdwjQjUWcEvwTZE6KaJLIIN6LLo9StImKYE37jH5ubo+PfnSdQlQdDcRWOJS5UwAun7Wr/i/ChN/o6UuLZxrEIFkJG96xWBdZiOHLzfpOORuUu6xWlVfaqLQ4i3fh4RJpFNnPgM1YQIf/xppvCpxl2XlivGzlmnajmewjuK55NYHhTT6ebSSRg7NjlqaVo73NSbS9kjx6vVNOc8PyIPz2Opjc0zHB+XoFDEXU+JJqjQno240spHS8mWzKEInf1hqU4zhT/UuXJ24pp45w72DaRSkrfAEry5+iOoDWXFcXSl/I4j+lYvaDScvd7PiQY7OFzxvauFDrSxqH/G6ydQIt46J0BbwE68IX8L0mHFpVz/igW9jC90RKK+2QJGpGr1t53ysX/Rq5JzJjBFwSIUB1IOV2/JsCWQ1zaXKK/CGlBk/bqaVSVARVc/H0wUCp0ilXbsiO+g9v7Bey3EI4QOI6EJW+JwBXJ9/6t5iYjArNr2du+2NWmMQR3MsSOvUqJngWEP0YF1ZqMMPrtr7CohFlmgGy3AQ0=
    - GO111MODULE=on

jobs:
  include:
  # --------------------------------------------
  - stage: test
    skip_cleanup: true
    script: 
      - make test
  # --------------------------------------------
  - stage: build
    skip_cleanup: true
    script:
      - make build
      - make run CMD=version
  # --------------------------------------------
  - stage: push:latest
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=latest
      on:
        branch: master
  # --------------------------------------------
  - stage: push:tag
    deploy:
      skip_cleanup: true
      provider: script
      script: make push TAG=$TRAVIS_TAG
      on:
        tags: true
  # --------------------------------------------
